services:
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    environment:
      - VITE_BACKEND_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
