version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
